### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by Margen67**
Example run: https://github.com/Margen67/extract-xiso/actions/runs/144404584

### CODE REVIEW

**Comment by Margen67** [comment]
> 
> 
> Can we have a 32 bit build for Windows?

@dracc Done.

**Comment by mborgerson** [comment]
Cool, thanks!

**Comment by GXTX** [comment]
@Margen67 RE: The ignore path's, we're ignoring all `*.yml`'s, wouldn't this ignore when the workflow is changed?

**Comment by Margen67** [comment]
> 
> 
> @Margen67 RE: The ignore path's, we're ignoring all `*.yml`'s, wouldn't this ignore when the workflow is changed?

It only does it for those in the root directory like appveyor.yml

**Pull request merged**
