### PR TITLE
AppVeyor: Upgrade to VS2019, parallel build, other changes

### PR DESCRIPTION
**Pull request by Margen67**

### CODE REVIEW

**Comment by mborgerson** [comment]
@Margen67 thanks!

AppVeyor was added to this repo before GitHub Actions existed. Now that we have support for cross-platform builds from your PR #38, I'd like to remove AppVeyor here altogether.

Since you filed both PRs at the same time, do you think there's a benefit to keeping AppVeyor around that GitHub Actions does not provide?

**Comment by Margen67** [comment]
> 
> 
> @Margen67 thanks!
> 
> AppVeyor was added to this repo before GitHub Actions existed. Now that we have support for cross-platform builds from your PR #38, I'd like to remove AppVeyor here altogether.
> 
> Since you filed both PRs at the same time, do you think there's a benefit to keeping AppVeyor around that GitHub Actions does not provide?

Artifacts from GitHub Actions can't be downloaded without being signed in to GitHub, and you can't create a link to the latest artifacts like you can with AppVeyor.

**Comment by mborgerson** [comment]
@Margen67 

> Artifacts from GitHub Actions can't be downloaded without being signed in to GitHub, and you can't create a link to the latest artifacts like you can with AppVeyor.

You can do this with GitHub releases

**Comment by Margen67** [comment]
> 
> 
> @Margen67
> 
> > Artifacts from GitHub Actions can't be downloaded without being signed in to GitHub, and you can't create a link to the latest artifacts like you can with AppVeyor.
> 
> You can do this with GitHub releases

I don't see any reason to keep AppVeyor, then.

**Pull request closed without merging**
