### PR TITLE
Fix for Redump/XGD ISOs and ISOs with empty directories

### PR DESCRIPTION
**Pull request by rapperskull**
First commit:
- Add support for XGD1/Redump ISOs
- Use correct offset when rewriting from XDG ISO (now it's possible to directly convert Redump ISOs to XISOs, unlike #46 and my previous attempt #45)
- Partially implement #33 (I don't think an '-o' option should be needed anymore)

Second commit:
- Don't fail on empty directories (Burnout (#25), [Project Gotham Racing](http://redump.org/disc/12614/))
- Write directory size as a multiple of sector size, as seen on retail ISOs (please note that this is in contrast to the [online sources on the matter](https://multimedia.cx/xdvdfs.html))
- Empty directories now use one sector instead of zero, as seen on retail ISOs
- Print empty directories in list mode

### CODE REVIEW

**Comment by rapperskull** [comment]
This should fix #33. BTW I now see there's already #46, but it doesn't address the offset problem when rewriting (it can only extract).

**Comment by rapperskull** [comment]
This should fix #25 by handling empty directories. Also, when writing an empty directory, write a sector filled with 0xFF instead of nothing, as seen in retail ISOs.

**Comment by rapperskull** [comment]
On retail ISOs, the directory size is a multiple of sector size. What I don't know is if an empty directory always occupies one sector, or if it's something non-standard Burnout did. The only source I managed to find is [this one](https://multimedia.cx/xdvdfs.html), that says size (and sector) should be zero.

**Comment by mnadareski** [comment]
I just want to chime in that this particular PR worked for a couple of corner-case discs that I have been having an issue with previously, including the aforementioned PGR. :heart:

**Comment by MasonT8198** [comment]
I have tested this PR, no issues that I can detect other than a known issue with extract-xiso where it can create bad isos as brought to my attention by Vaporeon

**Comment by MasonT8198** [comment]
PR #44 should be a suitable fix to the bad iso issue upon further research, will have to test to confirm the fix

**Review by LukeUsher — APPROVED** [review]
Looks good, thanks!

extract-xiso is basically on life-support at this point and in desperate need of a replacement, however, as it is one of the only open-source cross-platform solutions, this does need to be fixed.

**Pull request merged**
